### ISSUE TITLE
error in `geom_spi_rgb()` when using ` image_id` in `plotSpatialFeature()`

### ISSUE THREAD

**Issue by alikhuseynov** [pachterlab/voyager#11]
```
imgData(sfe)
DataFrame with 5 rows and 4 columns
     sample_id    image_id   data scaleFactor
   <character> <character> <list>   <numeric>
1 test.merfish  Cellbound1   ####           1
2 test.merfish  Cellbound2   ####           1
3 test.merfish  Cellbound3   ####           1
4 test.merfish        DAPI   ####           1
5 test.merfish       PolyT   ####           1

options(repr.plot.height = 5, repr.plot.width = 10)
pl1 <- 
plotSpatialFeature(sfe, features = "sum", 
                   size = 4, colGeometryName = "cellSeg", 
                   scattermore = TRUE, # will plot only centroids!
                   image_id = "DAPI" # 
                  ) & DarkTheme()
pl1

scattermore and binning only apply to points. Using centroids.
ERROR while rich displaying an object: Error in `geom_spi_rgb()`:
! Problem while converting geom to grob.
Error occurred in the 1st layer.
Caused by error in `rgb()`:
! color intensity 47180, not in 0:255
```
This error happen when using `image_id`.  Something to do with `max_col_value` in `Voyager:::geom_spi_rgb(., max_col_value = 255)`
any suggestions?
Thanks

**Comment by lambdamoses** [comment]
The bbox is unrelated to the maximum value in the image. Using a bounding box would still work with my 16 bit test image. Your bbox is

```
bbox_use <- c(xmin = 8300, xmax = 8000, ymin = -8300, ymax = -8000)
```

xmax is smaller than xmin, and that's the reason why it's invalid extent.

**Comment by lambdamoses** [comment]
Plus there's an argument in `plotSpatialFeature` for dark theme: `dark = TRUE`; it uses different default palettes from light theme so lighter color stands for higher value and stand out from the dark background.

**Comment by alikhuseynov** [comment]
ahh I see, Thanks! it works now. The confusion came from `flip` in `ReadVizgen()` since I was trying different combinations. By default `plotSpatialFeature()` doesn't show the axes, so I was adding `Seurat::DarkTheme()` which does the trick with less code. `dark = TRUE` is awesome 👍

**Comment by alikhuseynov** [comment]
is it easy to implement multiple overlapping images (eg, `terra::aggregate()`) to show, say `image_id = ("DAPI", "Cellbound1")` together?
I could take a look at some point as well.

**Comment by lambdamoses** [comment]
That's a good point. I can implement that. Doesn't seem difficult.

**Comment by alikhuseynov** [comment]
Thanks, especially, if one could use `> 2` images, like `image_id = ("DAPI", "Cellbound1", "Cellbound2")`
