### ISSUE TITLE
Local bivariate Moran's l (-log10p_adj Sim)  look the same

### ISSUE THREAD

**Issue by huiyijiangling** [pachterlab/voyager#36]
![image](https://github.com/pachterlab/voyager/assets/51966240/64e8fb63-6608-478e-94ef-8d5b7f744f8c)

Local bivariate Moran's l (-log10p_adj Sim)  look the same.

**Comment by lambdamoses** [comment]
Here the p-values come from Monte Carlo simulations with 1000 permutations; the p-values here only have 346 unique values. I used `all.equal` to check the p-values from `Myh1__Myh2` and `Ftl1__Myh2`; the values are similar but actually not all the same.
